version: '3.8'

services:
  frontend:
    build:
      context: ./client
    networks:
      - frontend
      - backend
  api:
    build:
      context: ./api
    depends_on:
      - mongo
    networks:
      - backend
  db:
    image: mongo
    restart: always
    networks:
      - backend
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
networks:
  frontend:
  backend: